title: TTNRT

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-toc
  - jekyll-last-modified-at

highlighter: rouge

exclude:
  - README.md
  - .gitignore

# set timezone
timezone: America/New_York

algolia:
  application_id: 'VUTR627QP3'
  index_name: 'ttnrt-search'