title: TTNRT

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-toc
  - jekyll-last-modified-at

highlighter: rouge

exclude:
  - README.md
  - .gitignore

last-modified-at:
    date-format: '%b %e, %l:%M %p'

